[package]
name = "rust-ls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte-unit = "4.0.14"
chrono = "0.4.22"
clap = { version = "3.2.21", features = ["derive"] }
thiserror = "1.0.34"
